config/routes.rb
Rails.application.routes.draw do
  resources :meetup_shops
  resources :meetups
  resources :points
  resources :reviews
  resources :shops
  resources :users
  get 'auth/:provider/callback', to: 'sessions#create'
  root to: 'top#index'
end

app/models/meetup.rb
class Meetup < ApplicationRecord
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :set_meetup, only: [:show, :edit, :update, :destroy]

  # GET /meetups
  # GET /meetups.json
  def index
    @meetups = Meetup.all
  end

  # GET /meetups/1
  # GET /meetups/1.json
  def show
  end

  # GET /meetups/new
  def new
    @meetup = Meetup.new
  end

  # GET /meetups/1/edit
  def edit
  end

  # POST /meetups
  # POST /meetups.json
  def create
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render :show, status: :created, location: @meetup }
      else
        format.html { render :new }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetups/1
  # PATCH/PUT /meetups/1.json
  def update
    respond_to do |format|
      if @meetup.update(meetup_params)
        format.html { redirect_to @meetup, notice: 'Meetup was successfully updated.' }
        format.json { render :show, status: :ok, location: @meetup }
      else
        format.html { render :edit }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetups/1
  # DELETE /meetups/1.json
  def destroy
    @meetup.destroy
    respond_to do |format|
      format.html { redirect_to meetups_url, notice: 'Meetup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meetup
      @meetup = Meetup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meetup_params
      params.require(:meetup).permit(:name, :start)
    end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/_form.html.erb
<%= form_with(model: meetup, local: true) do |form| %>
  <% if meetup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>

      <ul>
      <% meetup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetups/edit.html.erb
<h1>Editing Meetup</h1>

<%= render 'form', meetup: @meetup %>

<%= link_to 'Show', @meetup %> |
<%= link_to 'Back', meetups_path %>

app/views/meetups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetups.each do |meetup| %>
      <tr>
        <td><%= meetup.name %></td>
        <td><%= meetup.start %></td>
        <td><%= link_to 'Show', meetup %></td>
        <td><%= link_to 'Edit', edit_meetup_path(meetup) %></td>
        <td><%= link_to 'Destroy', meetup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meetup', new_meetup_path %>

app/views/meetups/new.html.erb
<h1>New Meetup</h1>

<%= render 'form', meetup: @meetup %>

<%= link_to 'Back', meetups_path %>

app/views/meetups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meetup.name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @meetup.start %>
</p>

<%= link_to 'Edit', edit_meetup_path(@meetup) %> |
<%= link_to 'Back', meetups_path %>